---

-  hosts: all
   tasks:
    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache2 package
      apt:
        name: apache2

    - name: install curl
      apt:
        name: curl

